name: HRIS Unit Test

on:
  push

env:
  HRIS_ACCESS_TOKEN: ${{ secrets.HRIS_ACCESS_TOKEN }}
  API_KEY: ${{ secrets.API_KEY }}

jobs:
  run-unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          override: true
      - name: run test
        run: cd merge-hris && cargo test